#!/bin/sh
EXPECTED_ARGS=1;
if [ $# -ne $EXPECTED_ARGS ]
then
  exit 1
fi
if [ $1 = unlock ]
then
  export QUERY_STRING="?ID=0&BoardType=V100&Description=Strike&Relay=1&Action=1"
  /mnt/apps/web/cgi-bin/diagnostics_execute.cgi
  #Uncomment to reventing others from relocking via diagnostics_execute.cgi
  #chmod -x /mnt/apps/web/cgi-bin/diagnostics_execute.cgi
else
  if [ $1 = lock ]
  then
    #If you uncommented the previous chmod, uncomment this one
    #chmod +x /mnt/apps/web/cgi-bin/diagnostics_execute.cgi
    export QUERY_STRING="?ID=0&BoardType=V100&Description=Strike&Relay=1&Action=0"
    /mnt/apps/web/cgi-bin/diagnostics_execute.cgi
  else
    exit 1
  fi
fi
